image: node:latest

stages:
    - staging

staging:
    type: deploy
    stage: staging
    script:
        - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
     only:
        - master




    
