cache:
  paths:
    - node_modules/

stages:
  - init
  - deploy_prod

init:
  stage: init
  image: node:12.16.1
  script:
    - npm install


deploy_production:
  image: node:12.16.1
  stage: deploy_prod
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/first-inmo-project1.git HEAD:master
    - echo "Deployed to production server"
  only:
    - master


    
